In [2]:
import torch
import numpy as np

a = torch.ones(3)
b = np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [8]:
a = torch.randint(10, (5,))
print(a)
c = (torch.randn(4, 1) * 2).long()
print(c)
b = a + c
print(b)
print(torch.mode(b,0))

tensor([9, 5, 7, 3, 2])
tensor([[-2],
        [-1],
        [ 0],
        [ 3]])
tensor([[ 7,  3,  5,  1,  0],
        [ 8,  4,  6,  2,  1],
        [ 9,  5,  7,  3,  2],
        [12,  8, 10,  6,  5]])
torch.return_types.mode(
values=tensor([7, 3, 5, 1, 0]),
indices=tensor([0, 0, 0, 0, 0]))


In [9]:
a = torch.load('train_test_indexes/splitted_indexes.pt')
print(a['test'])

tensor([3525, 3949, 4352, 3718, 4132,   42, 4396, 3831, 2993, 2680, 2716, 4471,
        1090,  535, 3358, 2800, 4715,  295, 4469, 2171, 2952,  715,  352, 4318,
        4747, 2477, 3070, 3218,  398, 1805, 2927, 4731, 2419, 2293, 2019, 3151,
         444, 3965,  667, 2456, 4624, 2115,  952, 4313, 3609,  523, 3824, 1775,
        4472, 1948, 3702, 1018, 4190, 1596, 1031, 4153,  705, 2766, 3330, 1672,
        4623, 2101, 3742, 4105, 1115, 3052, 1981, 1384, 1470, 2041,  325, 1142,
        2706, 3897, 3708,  834, 2274,  113, 1413,  264, 2229,  853, 1472, 2551,
        3450, 2841, 2064, 4460,  817,   11,  281, 3943,  727, 3505, 3633,  639,
        1295,  565, 1619, 3926, 4587, 1269, 4547,   78, 3427, 2096, 4292, 3361,
        3866, 2201, 2552, 2984, 3986, 3154, 2904, 1931, 3045, 2249, 3043,  556,
        4502, 2746, 3753, 4693, 4558, 3550, 2679,   26, 3262,  424,  782,  607,
         460,  407,  170, 1520, 1816, 2514, 3740,  186, 4301,  624, 3519,  251,
        1210, 3017,  871, 1608, 3623,  4

In [4]:
import torch

a = torch.ones(9,2).split(6)
print(a)

(tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]), tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]))


In [5]:
a = {}
a.update({'a':2})
print(a)

{'a': 2}


In [7]:
from tools.split_dataset import split_dataset
import numpy as np

imgs =torch.from_numpy(np.load('project_conic/CoNIC_Challenge/images.npy').astype(np.float64)/255).float().permute(0,3,1,2).contiguous()

split_dataset(imgs,'train_test_indexes/conic_trian_test_val_indexes.pt')